site_name: Fernando Celmer
site_url: https://www.fernandocelmer.com/
copyright: Fernando Celmer

nav:
    - Home: https://www.fernandocelmer.com/
    - Blog: index.md
    - Projects: projects.md
    - About: https://www.linkedin.com/in/fernando-celmer/
    - Yes Hello: post/2023/12/yes-hello.md

theme:
  name: simple-blog
  favicon: assets/favicon.ico
  theme_style: light
  site_name_style: normal
  title_style: bold
  components:
    site_name: false
    title: true
    menu: true
    preview: true
    footer: true

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js