site_name: Fernando Celmer
site_url: https://www.fernandocelmer.com/
copyright: Fernando Celmer

nav:
    - Home: https://www.fernandocelmer.com/
    - Blog: index.md
    - About: https://www.linkedin.com/in/fernando-celmer/

theme:
  name: simple-blog
  favicon: assets/favicon.ico
