site_name: Fernando Celmer
site_url: https://www.fernandocelmer.com/
copyright: Fernando Celmer

nav:
    - Home: https://www.fernandocelmer.com/
    - Blog: index.md

theme:
  name: simple-blog
  favicon: assets/favicon.ico
