site_name: Fernando Celmer
repo_name: FernandoCelmer/mkdocs-simple-blog
repo_url: https://github.com/FernandoCelmer/mkdocs-simple-blog
site_url: https://www.fernandocelmer.com/
copyright: Fernando Celmer

nav:
    - Home: https://www.fernandocelmer.com/
    - Blog: index.md

theme:
  name: simple-blog
  logo: assets/favicon.png
  favicon: assets/favicon.ico
